#!/usr/bin/python
import os, sys, logging
from utils.signal import Signal
from fw.fw import Firewall

fw_name = 'main-fw'

# Logging setup
log_level = logging.DEBUG	
logger = logging.getLogger('hooks-qemu')
fh = logging.FileHandler('/var/log/libvirt/hooks-qemu.log')
frmt = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

# Logging mapping
logger.setLevel(log_level)
fh.setLevel(log_level)
fh.setFormatter(frmt)
logger.addHandler(fh)	

if __name__ == "__main__": 
	logger.debug("Started qemu hook")
	vir_domain, action = sys.argv[1:3]

	fw = Firewall(fw_name, vir_domain)
	
	# Signaling data
	signaling = { 'start': Signal(), 'stop': Signal(), 'reconnect': Signal() }

	for k,v in signaling.items():
		''' Get signal for all objects '''
		mfw = getattr(fw, k)
		''' Connect all signals with their respective '''
		v.connect(mfw)

	logger.debug(action + " triggered... Sending signals")

	if action in ["stopped", "reconnect"]:
		signaling['stop'].fire()
	if action in ["start", "reconnect"]:
		signaling['start'].fire()
